# image: node:alpine  # a docker-image which loads the runtime environment
image: node:latest  # a docker-image which loads the runtime environment
image: aheuermann/electron:latest

stages:
  # all jobs for each stage are completed before moving to the next stage
  # - build
  - test

#cache:
#  # list paths to cache for performance boost
#  paths:
#    - DervetBackEnd/
#    # - DervetApp/node_modules/

before_script:
  # a list of commands to execute prior to each job
  - echo '... doing all before_script things ...'
  - Xvfb -ac -screen scrn 1280x2000x24 :9.0 &
  - export DISPLAY=:9.0
  - cd DervetApp
  # - node -v
  # - npm -v
  # - python3 -V
  - echo '... installing dependencies ...'
  - apt-get update && apt-get install -y --no-install-recommends --no-install-suggests libgtk-3-0 libxtst6 libxss1 libgconf-2-4 libnss3 libasound2 xvfb
  # - npm install -g @vue/cli
  # - npm install -g @vue/cli-init
  # - npm install
  - npm install gulp electron-prebuilt -g --no-progress --quiet --depth 0
  - npm install --no-progress --quiet --depth 0

test:
  # a job that executes in the test stage
  stage: test
  script:
    # a list of commands to execute in order
    - echo '... doing test ...'
    - npm test
  tags:
    - 'docker'  # invokes the docker-based group runner for EPRI Gitlab
