image: aheuermann/electron:latest
# NOTE: I found this docker image randomly online

stages:
  # all jobs for each stage are completed before moving to the next stage
  # - build
  - test

cache:
  # list paths to cache for performance boost
  paths:
    - DervetBackEnd/
    - DervetApp/node_modules/

before_script:
  # a list of commands to execute prior to each job
  - echo '... doing all before_script things ...'
  - Xvfb -ac -screen scrn 1280x2000x24 :9.0 &
  - export DISPLAY=:9.0
  - echo '... installing dependencies ...'
  - apt-get update && apt-get install -y --no-install-recommends --no-install-suggests libgtk-3-0
  - cd DervetApp
  - npm install --no-progress --quiet --depth 0

after_script:
  - node -v
  - npm -v
  - python3 -V

test:
  # a job that executes in the test stage
  stage: test
  script:
    # a list of commands to execute in order
    - echo '... doing test ...'
    - npm test
  tags:
    - 'docker'  # invokes the docker-based group runner for EPRI Gitlab
