// TODO use these constants in Results, Project, CalenvironScreen, and Appilcation

// Results mutations
export const RESET_RESULTS = 'RESET_RESULTS';

// Aplication mutations
export const MERGE_PAGE_STATUS = 'MERGE_PAGE_STATUS';
export const SET_PAGE_STATUS = 'SET_PAGE_STATUS';
export const SET_MANY_COLLECTION_PAGE_STATUS = 'SET_MANY_COLLECTION_PAGE_STATUS';
export const SET_RUN_IN_PROGRESS = 'SET_RUN_IN_PROGRESS';
export const SET_RUN_NOT_IN_PROGRESS = 'SET_RUN_NOT_IN_PROGRESS';
export const SET_RESULT_SUCCESS = 'SET_RESULT_SUCCESS';
export const SET_RESULT_ERROR = 'SET_RESULT_ERROR';
export const SET_NEW_APPLICATION_STATE = 'SET_NEW_APPLICATION_STATE';
export const RESET_APPLICATION = 'RESET_APPLICATION';
export const REMOVE_COLLECTION_PAGE_STATUS = 'REMOVE_COLLECTION_PAGE_STATUS';
export const REMOVE_ALL_COLLECTION_PAGE_STATUS = 'REMOVE_ALL_COLLECTION_PAGE_STATUS';

// Project mutations
export const SET_PROJECT = 'SET_PROJECT';
export const SET_ALL_VALUES_IN_TECH = 'SET_ALL_VALUES_IN_TECH';
export const SET_UNIQUE_IDS_IN_TECH = 'SET_UNIQUE_IDS_IN_TECH';
export const SET_VALUE = 'SET_VALUE';
export const ADD_COLLECTION_ITEM = 'ADD_COLLECTION_ITEM';
export const REMOVE_COLLECTION_ITEM = 'REMOVE_COLLECTION_ITEM';
export const REMOVE_ALL_COLLECTION_ITEMS = 'REMOVE_ALL_COLLECTION_ITEMS';
export const REPLACE_COLLECTION_ITEM = 'REPLACE_COLLECTION_ITEM';
export const ADD_MANY_COLLECTION_ITEMS = 'ADD_MANY_COLLECTION_ITEMS';
export const ACTIVATE_TECH = 'ACTIVATE_TECH';
export const DEACTIVATE_TECH = 'DEACTIVATE_TECH';
