// TODO use these constants in Results, Project, CalenvironScreen, and Appilcation


// Project actions
export const RESET_PROJECT_TO_DEFAULT = 'RESET_PROJECT_TO_DEFAULT';
export const LOAD_NEW_PROJECT = 'LOAD_NEW_PROJECT';
// battery page
export const REPLACE_TECHNOLOGY_SPECS_BATTERY = 'REPLACE_TECHNOLOGY_SPECS_BATTERY';
// battery cycle page
export const ADD_BATTERY_CYCLES_TO_TECHNOLOGY_SPECS_BATTERY = 'ADD_BATTERY_CYCLES_TO_TECHNOLOGY_SPECS_BATTERY';
// controllable load page
export const REPLACE_TECHNOLOGY_SPECS_CONTROLLABLE_LOAD = 'REPLACE_TECHNOLOGY_SPECS_CONTROLLABLE_LOAD';
// controllable load upload page
export const ADD_LOAD_PROFILE_TO_TECHNOLOGY_SPECS_CONTROLLABLE_LOAD = 'ADD_LOAD_PROFILE_TO_TECHNOLOGY_SPECS_CONTROLLABLE_LOAD';
// DA page
export const SET_DA_GROWTH = 'SET_DA_GROWTH';
export const SET_DA_PRICE = 'SET_DA_PRICE';

export const SET_DEFERRAL_GROWTH = 'SET_DEFERRAL_GROWTH';
export const SET_DEFERRAL_PRICE = 'SET_DEFERRAL_PRICE';
export const SET_DEFERRAL_PLANNED_LOAD_LIMIT = 'SET_DEFERRAL_PLANNED_LOAD_LIMIT';
export const SET_DEFERRAL_LOAD = 'SET_DEFERRAL_LOAD';
export const SET_DEFERRAL_REVERSE_POWER_FLOW_LIMIT = 'SET_DEFERRAL_REVERSE_POWER_FLOW_LIMIT';
// diesel gen page
export const REPLACE_TECHNOLOGY_SPECS_DIESEL_GEN = 'REPLACE_TECHNOLOGY_SPECS_DIESEL_GEN';
// fleet ev page
export const REPLACE_TECHNOLOGY_SPECS_FLEET_EV = 'REPLACE_TECHNOLOGY_SPECS_FLEET_EV';
// fleet ev upload page
export const ADD_LOAD_PROFILE_TO_TECHNOLOGY_SPECS_FLEET_EV = 'ADD_LOAD_PROFILE_TO_TECHNOLOGY_SPECS_FLEET_EV';

export const ADD_EXTERNAL_INCENTIVE = 'ADD_EXTERNAL_INCENTIVE';
export const REPLACE_EXTERNAL_INCENTIVES = 'REPLACE_EXTERNAL_INCENTIVES';
// technology spec page
export const ACTIVATE_TECH_BATTERY = 'ACTIVATE_TECH_BATTERY';
export const ACTIVATE_TECH_CONTROLLABLE_LOAD = 'ACTIVATE_TECH_CONTROLLABLE_LOAD';
export const ACTIVATE_TECH_DIESEL_GEN = 'ACTIVATE_TECH_DIESEL_GEN';
export const ACTIVATE_TECH_FLEET_EV = 'ACTIVATE_TECH_FLEET_EV';
export const ACTIVATE_TECH_ICE = 'ACTIVATE_TECH_ICE';
export const ACTIVATE_TECH_SINGLE_EV = 'ACTIVATE_TECH_SINGLE_EV';
export const ACTIVATE_TECH_SOLAR_PV = 'ACTIVATE_TECH_SOLAR_PV';
export const ADD_TECHNOLOGY_SPECS_BATTERY = 'ADD_TECHNOLOGY_SPECS_BATTERY';
export const ADD_TECHNOLOGY_SPECS_CONTROLLABLE_LOAD = 'ADD_TECHNOLOGY_SPECS_CONTROLLABLE_LOAD';
export const ADD_TECHNOLOGY_SPECS_DIESEL_GEN = 'ADD_TECHNOLOGY_SPECS_DIESEL_GEN';
export const ADD_TECHNOLOGY_SPECS_FLEET_EV = 'ADD_TECHNOLOGY_SPECS_FLEET_EV';
export const ADD_TECHNOLOGY_SPECS_ICE = 'ADD_TECHNOLOGY_SPECS_ICE';
export const ADD_TECHNOLOGY_SPECS_SINGLE_EV = 'ADD_TECHNOLOGY_SPECS_SINGLE_EV';
export const ADD_TECHNOLOGY_SPECS_SOLAR_PV = 'ADD_TECHNOLOGY_SPECS_SOLAR_PV';
export const ADD_TO_LIST_OF_ACTIVE_TECHNOLOGIES = 'ADD_TO_LIST_OF_ACTIVE_TECHNOLOGIES';
export const DEACTIVATE_TECH_BATTERY = 'DEACTIVATE_TECH_BATTERY';
export const DEACTIVATE_TECH_CONTROLLABLE_LOAD = 'DEACTIVATE_TECH_CONTROLLABLE_LOAD';
export const DEACTIVATE_TECH_DIESEL_GEN = 'DEACTIVATE_TECH_DIESEL_GEN';
export const DEACTIVATE_TECH_FLEET_EV = 'DEACTIVATE_TECH_FLEET_EV';
export const DEACTIVATE_TECH_ICE = 'DEACTIVATE_TECH_ICE';
export const DEACTIVATE_TECH_SINGLE_EV = 'DEACTIVATE_TECH_SINGLE_EV';
export const DEACTIVATE_TECH_SOLAR_PV = 'DEACTIVATE_TECH_SOLAR_PV';
export const REMOVE_TECH_BATTERY = 'REMOVE_TECH_BATTERY';
export const REMOVE_TECH_CONTROLLABLE_LOAD = 'REMOVE_TECH_CONTROLLABLE_LOAD';
export const REMOVE_TECH_DIESEL_GEN = 'REMOVE_TECH_DIESEL_GEN';
export const REMOVE_TECH_FLEET_EV = 'REMOVE_TECH_FLEET_EV';
export const REMOVE_TECH_ICE = 'REMOVE_TECH_ICE';
export const REMOVE_TECH_SINGLE_EV = 'REMOVE_TECH_SINGLE_EV';
export const REMOVE_TECH_SOLAR_PV = 'REMOVE_TECH_SOLAR_PV';
export const REPLACE_LIST_FIELD = 'REPLACE_LIST_FIELD';
export const RESET_LIST_OF_ACTIVE_TECHNOLOGIES = 'RESET_LIST_OF_ACTIVE_TECHNOLOGIES';
// user defined service
export const SET_USER_ENERGY_MAX = 'SET_USER_ENERGY_MAX';
export const SET_USER_ENERGY_MIN = 'SET_USER_ENERGY_MIN';
export const SET_USER_POWER_MAX = 'SET_USER_POWER_MAX';
export const SET_USER_POWER_MIN = 'SET_USER_POWER_MIN';
export const SET_USER_PRICE = 'SET_USER_PRICE';
